/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;
import Sistema.*;
import java.awt.Color;
import javax.swing.JPanel;
/**
 *
 * @author Edu Lopez
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Cramer
     */
    public Info() {
        initComponents();
        setLocationRelativeTo(null);//Aparesca en el centro
        setResizable(false);//No maximizar tamaño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jPOption = new javax.swing.JPanel();
        jLwelcometo = new javax.swing.JLabel();
        jLwelcometo2 = new javax.swing.JLabel();
        jLwelcometo4 = new javax.swing.JLabel();
        jLwelcometo5 = new javax.swing.JLabel();
        jLwelcometo6 = new javax.swing.JLabel();
        jLwelcometo8 = new javax.swing.JLabel();
        jLwelcometo9 = new javax.swing.JLabel();
        jLwelcometo12 = new javax.swing.JLabel();
        jLwelcometo13 = new javax.swing.JLabel();
        jLwelcometo14 = new javax.swing.JLabel();
        jLwelcometo15 = new javax.swing.JLabel();
        jPred = new javax.swing.JPanel();
        jLwelcometo1 = new javax.swing.JLabel();
        jPtop = new javax.swing.JPanel();
        jLbtnclose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPBackground.setBackground(new java.awt.Color(38, 38, 38));
        jPBackground.setToolTipText("");
        jPBackground.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPBackgroundFocusLost(evt);
            }
        });
        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPOption.setBackground(new java.awt.Color(75, 75, 75));
        jPOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLwelcometo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo.setText("Agregar nuevos registros desde la interfaz:");
        jPOption.add(jLwelcometo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, 20));

        jLwelcometo2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo2.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLwelcometo2.setText("Actualizaciones disponibles a la versión \"\"");
        jPOption.add(jLwelcometo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 30));

        jLwelcometo4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo4.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo4.setText("Mostrar datos en interfaz:");
        jPOption.add(jLwelcometo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 20));

        jLwelcometo5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo5.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo5.setText("Diseñador de Interfaz");
        jPOption.add(jLwelcometo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 20));

        jLwelcometo6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo6.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo6.setText("Eduardo Lopez(316030009@upjr.edu.mx)");
        jPOption.add(jLwelcometo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 20));

        jLwelcometo8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo8.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo8.setText("Eduardo Lopez (316030009@upjr.edu.mx)");
        jPOption.add(jLwelcometo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 20));

        jLwelcometo9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo9.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo9.setText("Institución: Universidad Politéctica de Juventino Rosas");
        jPOption.add(jLwelcometo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 300, 20));

        jLwelcometo12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo12.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo12.setText("Itzel Lera (316030008@upjr.edu.mx)");
        jPOption.add(jLwelcometo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, 20));

        jLwelcometo13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo13.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLwelcometo13.setText("Product Version: ");
        jPOption.add(jLwelcometo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 350, 30));

        jLwelcometo14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo14.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo14.setText("Creardor de Base de datos");
        jPOption.add(jLwelcometo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 20));

        jLwelcometo15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLwelcometo15.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo15.setText("Eduardo Lopez (316030009@upjr.edu.mx)");
        jPOption.add(jLwelcometo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 20));

        jPBackground.add(jPOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, 390));

        jPred.setBackground(new java.awt.Color(193, 44, 66));
        jPred.setToolTipText("");

        jLwelcometo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLwelcometo1.setForeground(new java.awt.Color(255, 255, 255));
        jLwelcometo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLwelcometo1.setText("LigaMX");

        javax.swing.GroupLayout jPredLayout = new javax.swing.GroupLayout(jPred);
        jPred.setLayout(jPredLayout);
        jPredLayout.setHorizontalGroup(
            jPredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLwelcometo1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPredLayout.setVerticalGroup(
            jPredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLwelcometo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBackground.add(jPred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, 60));

        jLbtnclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbtnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Images/Close Window_15px.png"))); // NOI18N
        jLbtnclose.setToolTipText("Cerrar? :'v");
        jLbtnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbtncloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPtopLayout = new javax.swing.GroupLayout(jPtop);
        jPtop.setLayout(jPtopLayout);
        jPtopLayout.setHorizontalGroup(
            jPtopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbtnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPtopLayout.setVerticalGroup(
            jPtopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbtnclose, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPBackground.add(jPtop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbtncloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbtncloseMousePressed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jLbtncloseMousePressed

    private void jPBackgroundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPBackgroundFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPBackgroundFocusLost
     void setColor(JPanel panel){
        panel.setBackground(new Color(204,204,204));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(240,240,240));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbtnclose;
    private javax.swing.JLabel jLwelcometo;
    private javax.swing.JLabel jLwelcometo1;
    private javax.swing.JLabel jLwelcometo12;
    private javax.swing.JLabel jLwelcometo13;
    private javax.swing.JLabel jLwelcometo14;
    private javax.swing.JLabel jLwelcometo15;
    private javax.swing.JLabel jLwelcometo2;
    private javax.swing.JLabel jLwelcometo4;
    private javax.swing.JLabel jLwelcometo5;
    private javax.swing.JLabel jLwelcometo6;
    private javax.swing.JLabel jLwelcometo8;
    private javax.swing.JLabel jLwelcometo9;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPOption;
    private javax.swing.JPanel jPred;
    private javax.swing.JPanel jPtop;
    // End of variables declaration//GEN-END:variables
}
