/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import MySQL.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edu Lopez
 */
public class MostrarDatos extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatos
     */
    int contador=0;
    public MostrarDatos() {
        initComponents();
        setLocationRelativeTo(null);//Aparesca en el centro
        setResizable(false);//No maximizar tamaño
        this.Temporadas.removeAllItems();//Seleccionar datos 
        this.Jornadas.removeAllItems();//Seleccionar datos 
        try{//ComboxTemporada
            Connection conexiont;
            conexiont=Conexion.getConexion();
            Statement Sent=conexiont.createStatement();
            ResultSet temporada= Sent.executeQuery("Select * from Temporada");
            while(temporada.next()){
                this.Temporadas.addItem(temporada.getString("Nom_torneo"));
            }
            //contador++;
        }catch(SQLException ex){
            JOptionPane.showInternalMessageDialog(null, ex); 
        }
        
        try{//ComboxJornada
            Connection conexionj;
            conexionj=Conexion.getConexion();
            Statement Sent=conexionj.createStatement();
            //ResultSet temporada= Sent.executeQuery("Select * from Temporada");
            ResultSet jornada= Sent.executeQuery("Select * from Jornada");
            while(jornada.next()){
                this.Jornadas.addItem(jornada.getString("Id_Jornada"));
            }
            contador++;
        }catch(SQLException ex){
            JOptionPane.showInternalMessageDialog(null, ex); 
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Temporadas = new javax.swing.JComboBox<>();
        Jornadas = new javax.swing.JComboBox<>();
        regresar = new javax.swing.JComboBox<>();
        prueba = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Temporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemporadasActionPerformed(evt);
            }
        });
        getContentPane().add(Temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 30));

        Jornadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Jornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JornadasActionPerformed(evt);
            }
        });
        getContentPane().add(Jornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 140, 30));

        regresar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regresar", "Menu Principal" }));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));
        getContentPane().add(prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 260, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 780, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/uefa.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemporadasActionPerformed
        // TODO add your handling code here:
        try{//ComboxJornada
            if(this.contador>0){
            Connection conexion;
            conexion=Conexion.getConexion();
            Statement Sent1=conexion.createStatement();
            ResultSet temp1=Sent1.executeQuery("Select * from temporada where Id_torneo= "+this.Jornadas.getSelectedItem()+" ");
            temp1.next();
                this.prueba.setText(String.valueOf(temp1.getString("Nom_torneo")));
        }
        } catch (SQLException ex) {
          Logger.getLogger(MostrarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemporadasActionPerformed

    private void JornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JornadasActionPerformed
        // TODO add your handling code here:
        
try{//ComboxJornada
            if(this.contador>0){
            Connection conexion1;
            conexion1=Conexion.getConexion();
            Statement Sent2=conexion1.createStatement();
            DefaultTableModel modelo = new DefaultTableModel();
            //ResultSet jor1=Sent2.executeQuery("Select * from Jornada where Id_jornada="+this.Jornadas.getSelectedItem()+" ");
            ResultSet rs = Database.getTabla("select t.Nom_torneo, j.Id_jornada,p.fecha_juegos ,eql.equipos ,p.marcador_local , p.marcador_visitante ,eqv.equipos , es.Nom_estadios from jornada as j INNER JOIN temporada as t on j.Id_torneo=t.Id_torneo INNER JOIN partidos as p on j.Id_jornada=p.Id_jornada INNER JOIN estadios as es on p.Id_estadios=es.Id_estadios INNER JOIN equipo as eql on p.equipo_local=eql.Id_equipos INNER JOIN equipo as eqv on p.equipo_visitante=eqv.Id_equipos where j.Id_jornada = "+this.Jornadas.getSelectedItem()+" ");
            modelo.setColumnIdentifiers(new Object[]{"Torneo", "Jornada", "Fecha de Juegos", "Local" , "Marcador" , "Marcador" , "Visitante" , "Estadio"});
            //jor1.next();
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo.addRow(new Object[]{rs.getString("Nom_torneo"), rs.getString("Id_jornada"),rs.getString("fecha_juegos"),rs.getString("eql.equipos"),rs.getString("marcador_local"),rs.getString("marcador_visitante"),rs.getString("eqv.equipos"),rs.getString("Nom_estadios")});
            }
            jTable1.setModel(modelo);    
            //this.jTextField1.setText(String.valueOf(jor1.getString("Id_jornada")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MostrarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JornadasActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        String regresa=(String)regresar.getSelectedItem();
        if(regresa.equals("Menu Principal")){
            Inicio obj=new Inicio();
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jornadas;
    private javax.swing.JComboBox<String> Temporadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField prueba;
    private javax.swing.JComboBox<String> regresar;
    // End of variables declaration//GEN-END:variables
}
